@component('dashboard::components.sidebarItem')
    @slot('url', route('dashboard.home'))
    @slot('name', trans('dashboard.home'))
    @slot('icon', 'fas fa-tachometer-alt')
    @slot('active', request()->routeIs('dashboard.home'))
@endcomponent

@include('dashboard.countries.partials.actions.sidebar')
@include('dashboard.currencies.partials.actions.sidebar')
@include('dashboard.accounts.sidebar')
@include('dashboard.brands.partials.actions.sidebar')
@include('dashboard.categories.partials.actions.sidebar')
@include('dashboard.products.partials.actions.sidebar')
@include('dashboard.collections.partials.actions.sidebar')
@include('dashboard.testers.partials.actions.sidebar')
@include('dashboard.coupons.partials.actions.sidebar')
@include('dashboard.orders.partials.actions.sidebar')
@include('dashboard.pages.partials.actions.sidebar')
@include('dashboard.settings.sidebar')